spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
